version: "3"
services:
  app:
    container_name: nuxt_utils_collection
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
       - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/nodemodules
volumes:
  node_modules: {}

